### ISSUE TITLE
Click Listener for the Plus and Minus.

### ISSUE THREAD

**Issue by moderateepheezy** [NSDavidObject/Stepperier#1]

**Comment by NSDavidObject** [comment]
@moderateepheezy did you try using the valueChanged action?

**Comment by moderateepheezy** [comment]
No, I meant, I want to be able to click plus and minus sign instead of just swiping, the swiping is a cool feature which is one of the reasons why I like te library.
Also, i also want to be able to change the plus and minus text colors.

**Comment by NSDavidObject** [comment]
Gotcha 👍

**Comment by NSDavidObject** [comment]
Both features have been incorporated as part of https://github.com/NSDavidObject/Stepperier/releases/tag/1.1.0 :)
